[package]
name = "comp-rs"
version = "0.4.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
bitflags = "1.3.2"
lazy_static = "1.4.0"


[lib]
name = "comp"
path = "src/lib.rs"
